[{"title":"neImageToolsD102Tokyo","key":"neImageToolsD102Tokyo","href":"neImageToolsD102Tokyo.htm","activate":true,"children":[{"title":"neImage","key":"neImage","href":"neImage.htm","children":[{"title":"Classes","key":"neImage_Classes","href":"neImage_Classes.htm","children":[{"title":"TneImage","key":"neImage.TneImage","href":"neImage.TneImage.htm","children":[{"title":"Constructors","key":"neImage.TneImage_Constructors","href":"neImage.TneImage_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neImage.TneImage.Create(TComponent)","href":"neImage.TneImage.Create.htm"}
]}
,{"title":"Properties","key":"neImage.TneImage_Properties","href":"neImage.TneImage_Properties.htm","children":[{"title":"BaseScale","key":"neImage.TneImage.BaseScale","href":"neImage.TneImage.BaseScale.htm"}
,{"title":"DelimiterString","key":"neImage.TneImage.DelimiterString","href":"neImage.TneImage.DelimiterString.htm"}
,{"title":"Directory","key":"neImage.TneImage.Directory","href":"neImage.TneImage.Directory.htm"}
,{"title":"FileExtension","key":"neImage.TneImage.FileExtension","href":"neImage.TneImage.FileExtension.htm"}
,{"title":"ImageTag","key":"neImage.TneImage.ImageTag","href":"neImage.TneImage.ImageTag.htm"}
,{"title":"Version","key":"neImage.TneImage.Version","href":"neImage.TneImage.Version.htm"}
]}
,{"title":"Methods","key":"neImage.TneImage_Methods","href":"neImage.TneImage_Methods.htm","children":[{"title":"Paint","key":"neImage.TneImage.Paint","href":"neImage.TneImage.Paint.htm"}
]}
,{"title":"Events","key":"neImage.TneImage_Events","href":"neImage.TneImage_Events.htm","children":[{"title":"OnGetBitmap","key":"neImage.TneImage.OnGetBitmap","href":"neImage.TneImage.OnGetBitmap.htm"}
]}
]}
]}
,{"title":"Delegates","key":"neImage_Delegates","href":"neImage_Delegates.htm","children":[{"title":"TOnGetBitmap","key":"neImage.TOnGetBitmap","href":"neImage.TOnGetBitmap.htm"}
]}
,{"title":"Constants","key":"neImage_Constants","href":"neImage_Constants.htm","children":[{"title":"BugVersion","key":"neImage.BugVersion","href":"neImage.BugVersion.htm"}
,{"title":"MajorVersion","key":"neImage.MajorVersion","href":"neImage.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neImage.MinorVersion","href":"neImage.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neImage_Routines","href":"neImage_Routines.htm","children":[{"title":"Register","key":"neImage.Register","href":"neImage.Register.htm"}
]}
]}
,{"title":"neImageList","key":"neImageList","href":"neImageList.htm","children":[{"title":"Classes","key":"neImageList_Classes","href":"neImageList_Classes.htm","children":[{"title":"TneImageList","key":"neImageList.TneImageList","href":"neImageList.TneImageList.htm","children":[{"title":"Constructors","key":"neImageList.TneImageList_Constructors","href":"neImageList.TneImageList_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neImageList.TneImageList.Create(TComponent)","href":"neImageList.TneImageList.Create.htm"}
,{"title":"Destroy","key":"neImageList.TneImageList.Destroy","href":"neImageList.TneImageList.Destroy.htm"}
]}
,{"title":"Properties","key":"neImageList.TneImageList_Properties","href":"neImageList.TneImageList_Properties.htm","children":[{"title":"BaseScale","key":"neImageList.TneImageList.BaseScale","href":"neImageList.TneImageList.BaseScale.htm"}
,{"title":"DelimiterString","key":"neImageList.TneImageList.DelimiterString","href":"neImageList.TneImageList.DelimiterString.htm"}
,{"title":"Directory","key":"neImageList.TneImageList.Directory","href":"neImageList.TneImageList.Directory.htm"}
,{"title":"FileExtension","key":"neImageList.TneImageList.FileExtension","href":"neImageList.TneImageList.FileExtension.htm"}
,{"title":"FilterTag","key":"neImageList.TneImageList.FilterTag","href":"neImageList.TneImageList.FilterTag.htm"}
,{"title":"OnLoadImages","key":"neImageList.TneImageList.OnLoadImages","href":"neImageList.TneImageList.OnLoadImages.htm"}
,{"title":"Version","key":"neImageList.TneImageList.Version","href":"neImageList.TneImageList.Version.htm"}
]}
,{"title":"Methods","key":"neImageList.TneImageList_Methods","href":"neImageList.TneImageList_Methods.htm","children":[{"title":"BeginUpdate","key":"neImageList.TneImageList.BeginUpdate","href":"neImageList.TneImageList.BeginUpdate.htm"}
,{"title":"createImageList","key":"neImageList.TneImageList.createImageList","href":"neImageList.TneImageList.createImageList.htm"}
,{"title":"EndUpdate","key":"neImageList.TneImageList.EndUpdate","href":"neImageList.TneImageList.EndUpdate.htm"}
,{"title":"loadDirectories","key":"neImageList.TneImageList.loadDirectories","href":"neImageList.TneImageList.loadDirectories.htm"}
,{"title":"loadImageList","key":"neImageList.TneImageList.loadImageList","href":"neImageList.TneImageList.loadImageList.htm"}
,{"title":"loadImages","key":"neImageList.TneImageList.loadImages","href":"neImageList.TneImageList.loadImages.htm"}
]}
]}
]}
,{"title":"Constants","key":"neImageList_Constants","href":"neImageList_Constants.htm","children":[{"title":"BugVersion","key":"neImageList.BugVersion","href":"neImageList.BugVersion.htm"}
,{"title":"MajorVersion","key":"neImageList.MajorVersion","href":"neImageList.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neImageList.MinorVersion","href":"neImageList.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neImageList_Routines","href":"neImageList_Routines.htm","children":[{"title":"Register","key":"neImageList.Register","href":"neImageList.Register.htm"}
]}
]}
,{"title":"neImageList.Utils","key":"neImageList.Utils","href":"neImageList.Utils.htm","children":[{"title":"Routines","key":"neImageList.Utils_Routines","href":"neImageList.Utils_Routines.htm","children":[{"title":"processDirectories(string,string,string,TList)","key":"neImageList.Utils.processDirectories(string,string,string,TList)","href":"neImageList.Utils.processDirectories.htm"}
,{"title":"processImageList(TDictionary,single,Pointer,TNotifyEvent)","key":"neImageList.Utils.processImageList(TDictionary,single,Pointer,TNotifyEvent)","href":"neImageList.Utils.processImageList.htm"}
,{"title":"processImages(string,TList,TDictionary)","key":"neImageList.Utils.processImages(string,TList,TDictionary)","href":"neImageList.Utils.processImages.htm"}
]}
]}
,{"title":"neImageTools.Types","key":"neImageTools.Types","href":"neImageTools.Types.htm","children":[{"title":"Constants","key":"neImageTools.Types_Constants","href":"neImageTools.Types_Constants.htm","children":[{"title":"defaultScale","key":"neImageTools.Types.defaultScale","href":"neImageTools.Types.defaultScale.htm"}
]}
]}
]}
]