//***************************************************************
//
// Version History
//
// 1.1.0 - 28/10/2018
//	   * New Features
//	     - New neImage component added
//     
// 1.0.1 - 26/10/2018
//
//	   * Bug fixes
//           - An assignment to var did not compile on Android  	
//
// 1.0.0 - Initial Version (24/10/2018)
//***************************************************************


{$HINTS OFF}
const
  MajorVersion = '1';
  MinorVersion = '1';
  BugVersion = '0';
{$HINTS ON}
